# Generated by Django 5.2.6 on 2025-11-05 11:58

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id_stage', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZÀ-ÿ\\s]+$', 'Le titre ne doit contenir que des lettres et des espaces.')])),
                ('description', models.TextField()),
                ('localisation', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZÀ-ÿ\\s,]+$', 'La localisation ne doit contenir que des lettres, espaces et virgules.')])),
                ('duree', models.PositiveIntegerField(help_text='Durée du stage en semaines')),
                ('date_publication', models.DateField(default=datetime.date.today)),
                ('type', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Le type doit contenir uniquement des lettres et espaces.')])),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='userapp.entreprise')),
            ],
        ),
    ]
