# Generated by Django 5.2.6 on 2025-11-14 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelance',
            fields=[
                ('id_freelance', models.AutoField(primary_key=True, serialize=False)),
                ('titre_mission', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('competences_requises', models.CharField(max_length=200)),
                ('tarif', models.FloatField()),
                ('duree_estimee', models.IntegerField()),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('domaine', models.CharField(choices=[('IT', 'Informatique / Développement'), ('MARKETING', 'Marketing / Communication'), ('DESIGN', 'Design / Graphisme'), ('FINANCE', 'Finance / Comptabilité'), ('RH', 'Ressources Humaines'), ('TRAD', 'Traduction / Rédaction'), ('EDUCATION', 'Éducation / Formation'), ('AUTRE', 'Autre')], default='IT', max_length=50)),
                ('id_entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freelances', to='userapp.entreprise')),
            ],
        ),
    ]
