# Generated by Django 5.2.6 on 2025-11-05 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelance',
            name='id_entreprise',
        ),
        migrations.AddField(
            model_name='freelance',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freelances', to=settings.AUTH_USER_MODEL),
        ),
    ]
