# Generated by Django 5.2.6 on 2025-11-05 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formationapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id_particip', models.AutoField(primary_key=True, serialize=False)),
                ('date_particip', models.DateField(auto_now_add=True)),
                ('id_formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='formationapp.formation')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
