# Generated by Django 5.2.6 on 2025-11-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_domain_skill_candidat_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Management', 'Management')], max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('name', 'domain')},
        ),
    ]
