# Generated by Django 5.2.6 on 2025-11-15 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_languageoption_remove_language_candidat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidat',
            options={},
        ),
        migrations.CreateModel(
            name='CandidatLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=5)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.candidat')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.languageoption')),
            ],
            options={
                'unique_together': {('candidat', 'language')},
            },
        ),
        migrations.AddField(
            model_name='candidat',
            name='languages',
            field=models.ManyToManyField(blank=True, through='userapp.CandidatLanguage', to='userapp.languageoption'),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
