# Generated by Django 5.2.6 on 2025-11-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_candidat_options_candidatlanguage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='languages',
        ),
        migrations.DeleteModel(
            name='CandidatLanguage',
        ),
        migrations.DeleteModel(
            name='LanguageOption',
        ),
        migrations.AddField(
            model_name='candidat',
            name='languages',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
