# Generated by Django 5.2.6 on 2025-11-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_domain_name_alter_skill_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('domain', 'name')},
        ),
    ]
