# Generated by Django 5.2.6 on 2025-11-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_candidat_options_remove_candidat_languages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='utilisateur',
            new_name='Candidat',
        ),
    ]
