# Generated by Django 5.2.6 on 2025-11-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_rename_utilisateur_language_candidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='languages',
            field=models.ManyToManyField(blank=True, to='userapp.language'),
        ),
    ]
