# Generated by Django 5.2.6 on 2025-11-15 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_candidat_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='language',
            name='Candidat',
        ),
        migrations.AddField(
            model_name='language',
            name='candidat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.candidat'),
        ),
    ]
