# Generated by Django 5.2.6 on 2025-11-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_remove_candidat_languages_remove_language_candidat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
