# Generated by Django 5.2.6 on 2025-11-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_delete_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
