# Generated by Django 5.2.6 on 2025-11-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_entreprise_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
