# Generated by Django 5.2.6 on 2025-11-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_entreprise_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='entreprises/logos/'),
        ),
    ]
