# Generated by Django 5.2.6 on 2025-11-05 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id_formation', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('niveau', models.CharField(choices=[('DEBUTANT', 'Debutant'), ('INTERMEDIAIRE', 'Intermediaire'), ('AVANCE', 'Avancé')], default='DEBUTANT', max_length=30)),
                ('categorie', models.CharField(choices=[('IT', 'Informatique / Développement'), ('MARKETING', 'Marketing / Communication'), ('DESIGN', 'Design / Graphisme'), ('FINANCE', 'Finance / Comptabilité'), ('RH', 'Ressources Humaines'), ('TRAD', 'Traduction / Rédaction'), ('EDUCATION', 'Éducation / Formation'), ('AUTRE', 'Autre')], default='IT', max_length=50)),
                ('duree', models.IntegerField(help_text='Durée en heures')),
                ('certif', models.BooleanField(default=False)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
