# Generated by Django 5.2.8 on 2025-11-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='formation/'),
        ),
    ]
