# Generated by Django 5.2.8 on 2025-11-12 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formationapp', '0002_formation_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='img',
            new_name='image',
        ),
    ]
