# Generated by Django 5.2.8 on 2025-11-12 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formationapp', '0003_rename_img_formation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='formation',
            name='duree',
            field=models.PositiveBigIntegerField(help_text='Durée en heures'),
        ),
    ]
