# Generated by Django 5.2.8 on 2025-11-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formationapp', '0004_alter_formation_description_alter_formation_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='duree',
            field=models.PositiveBigIntegerField(),
        ),
    ]
