# Generated by Django 5.2.8 on 2025-11-19 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formationapp', '0005_alter_formation_duree'),
    ]

    operations = [
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id_lesson', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('file', models.FileField(upload_to='lessons/')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='formationapp.formation')),
            ],
        ),
    ]
