# Generated by Django 5.2.8 on 2025-11-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formationapp', '0007_lesson_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='titre',
            field=models.CharField(),
        ),
    ]
