import os
import re
import json
from pathlib import Path
from datetime import datetime

import pandas as pd

from .evaluator import compute_text_quality_scores
from .document_parser import split_candidate_requirements
from .utils import SRS_DATA_DIR, SRS_OUTPUTS_DIR, safe_read_csv, detect_column


def _value_counts(df, candidate_cols):
    if df is None or df.empty:
        return {}

    col = detect_column(df, candidate_cols)
    if not col:
        return {}

    return df[col].astype(str).value_counts().to_dict()


def _numeric_mean(df, candidate_cols):
    if df is None or df.empty:
        return None

    col = detect_column(df, candidate_cols)
    if not col:
        return None

    values = pd.to_numeric(df[col], errors="coerce").dropna()
    if values.empty:
        return None

    return round(float(values.mean()), 2)


def _safe_preview_rows(df, max_rows=8):
    if df is None or df.empty:
        return []

    preview = df.head(max_rows).copy()
    return preview.astype(str).to_dict(orient="records")


def load_notebook_model_outputs():
    """
    Load deployed outputs generated by previous notebooks.
    These files represent the real outputs of DistilBERT, RoBERTa,
    ResNet/CV, LLM rewriting, quality scoring, and XAI modules.
    """

    files = {
        "fr_nfr": "c6_deep_fr_nfr_predictions.csv",
        "nfr_subtype": "c7_nfr_subtype_predictions.csv",
        "ambiguity": "c8_deep_ambiguity_predictions.csv",
        "quality": "c9_multimodal_requirement_quality_scores.csv",
        "rewrites": "c10_llm_requirement_rewrites.csv",
        "final_report": "c11_final_requirement_report.csv",
        "vision": "v7_page_vision_predictions.csv",
        "document_ambiguity": "c8_document_ambiguity_summary.csv",
        "document_quality": "c11_final_document_report.csv",
        "toc": "c4_toc_consistency_final.csv",
    }

    loaded = {}

    for key, filename in files.items():
        path = SRS_DATA_DIR / filename
        loaded[key] = safe_read_csv(path)

    return loaded


def summarize_fr_nfr(df):
    return {
        "model": "DistilBERT FR/NFR classifier",
        "description": "Classifies candidate requirements as functional, non-functional, or uncertain.",
        "distribution": _value_counts(df, [
            "final_prediction",
            "deep_prediction_label",
            "deep_prediction",
            "prediction",
            "requirement_type_candidate",
        ]),
        "sample_predictions": _safe_preview_rows(df, 5),
    }


def summarize_nfr_subtypes(df):
    return {
        "model": "RoBERTa NFR subtype classifier",
        "description": "Classifies non-functional requirements into subtypes such as security, usability, performance, reliability, maintainability, scalability, etc.",
        "distribution": _value_counts(df, [
            "nfr_subtype_pred",
            "nfr_subtype",
            "subtype",
            "predicted_subtype",
        ]),
        "sample_predictions": _safe_preview_rows(df, 5),
    }


def summarize_ambiguity(df):
    return {
        "model": "RoBERTa ambiguity detector",
        "description": "Detects CLEAR, AMBIGUOUS, or UNCERTAIN requirements.",
        "distribution": _value_counts(df, [
            "final_ambiguity_label",
            "ambiguity_label",
            "prediction",
            "ambiguity_prediction",
        ]),
        "sample_predictions": _safe_preview_rows(df, 5),
    }


def summarize_quality(df):
    avg_quality = _numeric_mean(df, [
        "requirement_quality_score",
        "deep_quality_numeric_score",
        "quality_score",
        "final_quality_score",
    ])

    quality_distribution = _value_counts(df, [
        "requirement_quality_level",
        "quality_level",
        "deep_quality_label",
        "final_quality_label",
    ])

    return {
        "model": "RoBERTa / multimodal requirement quality classifier",
        "description": "Scores requirement quality using textual, structural, ambiguity, and visual context signals.",
        "average_quality_score": avg_quality,
        "quality_distribution": quality_distribution,
        "sample_quality_rows": _safe_preview_rows(df, 5),
    }


def summarize_rewrites(df):
    if df is None or df.empty:
        return {
            "model": "LLM requirement rewriting",
            "description": "No rewrite output file found.",
            "rewrite_count": 0,
            "sample_rewrites": [],
        }

    return {
        "model": "LLM requirement rewriting and validation",
        "description": "Improves weak, ambiguous, incomplete, or low-quality requirements.",
        "rewrite_count": int(len(df)),
        "sample_rewrites": _safe_preview_rows(df, 8),
    }


def summarize_vision(df):
    return {
        "model": "ResNet18 / CV page classifier",
        "description": "Classifies SRS pages visually and provides page-level document structure signals.",
        "page_type_distribution": _value_counts(df, [
            "predicted_page_type",
            "page_type",
            "prediction",
            "final_prediction",
        ]),
        "average_confidence": _numeric_mean(df, [
            "confidence",
            "vision_confidence",
            "prediction_confidence",
            "max_probability",
        ]),
        "sample_pages": _safe_preview_rows(df, 5),
    }


def summarize_xai(outputs):
    lime_available = (
        not outputs.get("fr_nfr", pd.DataFrame()).empty
        or not outputs.get("nfr_subtype", pd.DataFrame()).empty
        or not outputs.get("ambiguity", pd.DataFrame()).empty
    )

    gradcam_available = not outputs.get("vision", pd.DataFrame()).empty

    return {
        "lime": {
            "available": bool(lime_available),
            "description": "LIME explanations are associated with NLP classifiers such as FR/NFR, NFR subtype, and ambiguity detection.",
            "used_for": [
                "Explain important words influencing FR/NFR predictions",
                "Explain NFR subtype classification",
                "Explain ambiguity detection decisions",
            ],
        },
        "gradcam": {
            "available": bool(gradcam_available),
            "description": "Grad-CAM explanations are associated with the ResNet/CV page classifier.",
            "used_for": [
                "Highlight visual regions used for page type prediction",
                "Support explainability for scanned or image-based SRS pages",
            ],
        },
        "global_explanation": "The evaluation combines rule-based SRS quality checks with trained model outputs and XAI summaries from previous notebooks.",
    }


def compute_model_aware_score(rule_eval, model_summary):
    """
    Combines text-rule evaluation with notebook model signals.
    This is the deployed aggregation layer.
    """

    base_score = float(rule_eval.get("overall_score", 0))

    quality_score = model_summary.get("quality", {}).get("average_quality_score")
    if quality_score is None:
        quality_score = base_score

    ambiguity_distribution = model_summary.get("ambiguity", {}).get("distribution", {})
    total_amb = sum(ambiguity_distribution.values()) if ambiguity_distribution else 0
    ambiguous = 0

    for key, value in ambiguity_distribution.items():
        if "AMBIG" in str(key).upper() or "UNCERTAIN" in str(key).upper():
            ambiguous += value

    ambiguity_penalty = 0
    if total_amb:
        ambiguity_penalty = min(20, (ambiguous / total_amb) * 20)

    final_score = round(
        0.45 * base_score
        + 0.35 * float(quality_score)
        + 0.20 * max(0, 100 - ambiguity_penalty),
        2,
    )

    if final_score >= 85:
        label = "EXCELLENT_MODEL_AWARE_SRS"
    elif final_score >= 70:
        label = "GOOD_MODEL_AWARE_SRS"
    elif final_score >= 55:
        label = "ACCEPTABLE_MODEL_AWARE_SRS"
    else:
        label = "NEEDS_MAJOR_IMPROVEMENT"

    return {
        "final_model_aware_score": final_score,
        "final_model_aware_label": label,
        "base_rule_score": base_score,
        "average_model_quality_score": quality_score,
        "ambiguity_penalty": round(ambiguity_penalty, 2),
        "score_formula": "0.45 * rule_score + 0.35 * multimodal_quality_score + 0.20 * ambiguity_adjusted_score",
    }


def build_model_recommendations(rule_eval, model_summary):
    recommendations = list(rule_eval.get("recommendations", []))

    ambiguity_distribution = model_summary.get("ambiguity", {}).get("distribution", {})
    if any("AMBIG" in str(k).upper() for k in ambiguity_distribution.keys()):
        recommendations.append("Review ambiguous requirements detected by the RoBERTa ambiguity model.")

    nfr_distribution = model_summary.get("nfr_subtypes", {}).get("distribution", {})
    if nfr_distribution:
        recommendations.append("Validate NFR subtype coverage, especially security, performance, usability, availability, and maintainability.")

    quality_score = model_summary.get("quality", {}).get("average_quality_score")
    if quality_score is not None and quality_score < 75:
        recommendations.append("Use the LLM rewriting outputs to improve low-quality requirements before final validation.")

    vision_distribution = model_summary.get("vision", {}).get("page_type_distribution", {})
    if vision_distribution:
        recommendations.append("Use the ResNet/CV page classification outputs to verify document structure, cover page, TOC, content pages, and appendices.")

    return list(dict.fromkeys(recommendations))


def save_evaluation_report(report):
    SRS_OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)

    project_slug = "srs_model_based_evaluation"
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    json_path = SRS_OUTPUTS_DIR / f"{project_slug}_{timestamp}.json"
    md_path = SRS_OUTPUTS_DIR / f"{project_slug}_{timestamp}.md"
    pdf_path = SRS_OUTPUTS_DIR / f"{project_slug}_{timestamp}.pdf"

    json_path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")

    rule_eval = report.get("rule_based_evaluation", {})
    detected_sections = rule_eval.get("detected_sections", []) or []
    missing_sections = rule_eval.get("missing_sections", []) or []
    detected_vague_terms = rule_eval.get("detected_vague_terms", []) or []
    vague_contexts = rule_eval.get("vague_term_contexts", []) or []
    uploaded_visual = (
        report.get("uploaded_visual_classification")
        or report.get("model_based_evaluation", {}).get("uploaded_vision")
    )

    vague_terms_md = "No vague terms detected."
    if detected_vague_terms:
        vague_terms_md = "\n".join([
            f"- {item.get('term')}: {item.get('count')} occurrence(s)"
            for item in detected_vague_terms
        ])

    vague_contexts_md = "No vague-term context available."
    if vague_contexts:
        vague_contexts_md = "\n".join([
            f"- {item.get('term')}: {item.get('sentence')}"
            for item in vague_contexts[:20]
        ])

    uploaded_visual_md = "No uploaded image/PDF visual classification was attached to this report."
    if uploaded_visual:
        page_rows = uploaded_visual.get("page_predictions", []) or []
        page_md = "\n".join([
            f"- Page {row.get('page_number')}: {row.get('display_page_type') or row.get('predicted_page_type')} "
            f"(confidence: {row.get('confidence')}, source: {row.get('source')})"
            for row in page_rows
        ]) or "No page-level prediction available."

        uploaded_visual_md = f"""- File: {uploaded_visual.get('input_file')}
- Predicted type: {uploaded_visual.get('overall_uploaded_document_type_display') or uploaded_visual.get('overall_uploaded_document_type')}
- Confidence: {uploaded_visual.get('confidence')}
- Source: {uploaded_visual.get('source')}
- ResNet status: {uploaded_visual.get('resnet_status')}

### Page-level predictions

{page_md}"""

    md = f"""# Model-Based SRS Evaluation Report

Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Final Score

- Score: {report["model_aware_score"]["final_model_aware_score"]}
- Label: {report["model_aware_score"]["final_model_aware_label"]}

## Rule-Based Evaluation

- Overall score: {rule_eval.get("overall_score")}
- Completeness: {rule_eval.get("completeness_score")}
- Clarity: {rule_eval.get("clarity_score")}
- Consistency: {rule_eval.get("consistency_score")}
- Testability: {rule_eval.get("testability_score")}
- Feasibility: {rule_eval.get("feasibility_score")}
- Requirement-like sentences: {rule_eval.get("requirements_count")}
- Vague / unclear terms: {rule_eval.get("vague_terms_count")}

## Detected SRS Sections

{chr(10).join([f"- {section}" for section in detected_sections]) if detected_sections else "No standard SRS section detected."}

## Missing SRS Sections

{chr(10).join([f"- {section}" for section in missing_sections]) if missing_sections else "No standard SRS section appears to be missing."}

## Vague or Unclear Terms Detected

{vague_terms_md}

## Vague-Term Contexts

{vague_contexts_md}

## Uploaded Image/PDF ResNet-CV Classification

{uploaded_visual_md}

## Model Outputs Used

- DistilBERT FR/NFR
- RoBERTa NFR subtype
- RoBERTa ambiguity detection
- RoBERTa / multimodal quality classifier
- ResNet18 / CV page classifier
- LLM rewriting outputs
- LIME and Grad-CAM summaries

## Recommendations

{chr(10).join([f"- {r}" for r in report["recommendations"]])}
"""

    md_path.write_text(md, encoding="utf-8")

    try:
        import fitz
        import textwrap

        pdf_doc = fitz.open()
        page = pdf_doc.new_page()
        margin = 40
        y = margin
        line_height = 14
        font_size = 9

        for raw_line in md.splitlines():
            wrapped_lines = textwrap.wrap(raw_line, width=100) or [""]

            for line in wrapped_lines:
                if y > page.rect.height - margin:
                    page = pdf_doc.new_page()
                    y = margin

                page.insert_text(
                    (margin, y),
                    line,
                    fontsize=font_size,
                    fontname="helv",
                )
                y += line_height

        pdf_doc.save(str(pdf_path))
        pdf_doc.close()

    except Exception as e:
        print(f"[WARN] PDF report generation failed: {e}")
        pdf_path = None

    files = {
        "json": str(json_path),
        "markdown": str(md_path),
    }

    if pdf_path and pdf_path.exists():
        files["pdf"] = str(pdf_path)

    return files
def evaluate_srs_with_models(text):
    rule_eval = compute_text_quality_scores(text)
    requirements = split_candidate_requirements(text)

    outputs = load_notebook_model_outputs()

    model_summary = {
        "fr_nfr": summarize_fr_nfr(outputs["fr_nfr"]),
        "nfr_subtypes": summarize_nfr_subtypes(outputs["nfr_subtype"]),
        "ambiguity": summarize_ambiguity(outputs["ambiguity"]),
        "quality": summarize_quality(outputs["quality"]),
        "rewrites": summarize_rewrites(outputs["rewrites"]),
        "vision": summarize_vision(outputs["vision"]),
        "xai": summarize_xai(outputs),
    }

    model_score = compute_model_aware_score(rule_eval, model_summary)
    recommendations = build_model_recommendations(rule_eval, model_summary)

    report = {
        "status": "success",
        "message": "SRS evaluated successfully using rule-based checks and deployed notebook model outputs.",
        "input_statistics": {
            "text_length": len(text),
            "detected_requirement_sentences": len(requirements),
        },
        "rule_based_evaluation": rule_eval,
        "model_based_evaluation": model_summary,
        "model_aware_score": model_score,
        "recommendations": recommendations,
    }

    report["report_files"] = save_evaluation_report(report)

    return report